@BASE_URL = http://localhost:4000

### สมัครการใช้งาน User
POST {{BASE_URL}}/auth/register/user
Content-Type: application/json

{
    "username":"bedsds",
    "password":"12s3456"
}

###สมัครการใช้งาน docter
POST {{BASE_URL}}/auth/register/docter
Content-Type: application/json

{
"username":"test1",
"password":"234df34"
}

###
# @name loginUser
POST {{BASE_URL}}/auth/login/User
Content-Type: application/json

{
"username":"bedsds",
"password":"12s3456"
}
